Windmill + load objects with bridges
aerostack2/aerostack2 pull request #145
Opened 2023-01-26 17:12 UTC by javilinos

Added working windmill model, added feature to load object with bridges into the world from config file.

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   | #140 |
| ROS2 version tested on |Humble|
| Aerial platform tested on | Ignition|

---

## Description of contribution in a few bullet points

* Added Windmill model with joint force and publisher plugins to assets.
* Organized models into drone models and object models. 
* Ability to load objects with bridges into the world.

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

* Easier way to register/map new objects/sensors to bridges from outside the source code.

2023-01-26 17:14 UTC, javilinos commented
Feature is implemented but there might be better ways to structure code in ign_assets, @pariaspe check it out and we talk.

2023-01-30 11:17 UTC, pariaspe requested changes
Nice job! I've just added some minor corrections, check them out

2023-01-30 11:17 UTC, pariaspe commented on as2_aerial_platforms/as2_platform_ign_gazebo/launch/ign_gazebo_launch.py
> +    object_bridges = IncludeLaunchDescription(
do not launch object bridges with drone platform

2023-01-30 11:17 UTC, pariaspe commented on as2_simulation_assets/as2_ign_gazebo_assets/launch/launch_simulation.py
>      launch_processes.extend(world_bridges())
add object_bridges here

2023-01-30 11:17 UTC, pariaspe commented on as2_simulation_assets/as2_ign_gazebo_assets/models/windmill/windmill.sdf.jinja
> +    <model name='{{ namespace }}'>
why are you using jinja? just for the namespace?

2023-01-30 11:17 UTC, pariaspe commented on as2_simulation_assets/as2_ign_gazebo_assets/src/ign_assets/model.py
> +def windmill_models():
not only for windmills models, rename method name with a more generic one

2023-01-30 11:17 UTC, pariaspe commented on as2_simulation_assets/as2_ign_gazebo_assets/worlds/windmill_world.sdf
> +
Isn't this an empty.world?

2023-02-13 07:47 UTC, miferco97 commented
@pariaspe  is this ready for merge?

2023-02-20 11:45 UTC, pariaspe approved these changes

2023-02-20 11:45 UTC, merged