Cf demo gates
aerostack2/aerostack2 pull request #154
Opened 2023-02-16 09:43 UTC by RPS98

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   | - |
| ROS2 version tested on | Humble) |
| Aerial platform tested on | Ignition, Crazyflie |

---

## Description of contribution in a few bullet points

* Add behavior manager to python API
* Add behavior manager to keyboard teleoperation
* Fix crazyflie platform launcher and odometry publisher
* Adjust land speed goal check parameters
* Add trajectory generator behavior pause and resume features

2023-02-16 10:04 UTC, miferco97 requested changes

2023-02-16 10:04 UTC, miferco97 commented on as2_behaviors/as2_behaviors_motion/land_behavior/plugins/land_plugin_speed.cpp
> +  float height_threshold_ = 0.2;
Why this is not a parameter?

2023-02-16 10:04 UTC, miferco97 commented on as2_behaviors/as2_behaviors_motion/land_behavior/plugins/land_plugin_speed.cpp
> +    speed_condition_ = _goal.land_speed * 0.2;
why this hardcoded numbers ?

2023-02-16 10:04 UTC, miferco97 commented on as2_behaviors/as2_behaviors_trajectory_generator/dynamic_polynomial_trajectory_generator/src/dynamic_polynomial_trajectory_generator.cpp
> -  // if (goal->trajectory_waypoints.header.frame_id != desired_frame_id_) {
how are frames considered now  ?

2023-02-16 10:04 UTC, miferco97 commented on as2_behaviors/as2_behaviors_trajectory_generator/dynamic_polynomial_trajectory_generator/src/dynamic_polynomial_trajectory_generator.cpp
> -  // // First waypoint is current position
Remove this comment if  uncommenting these produces a bug

2023-02-16 10:08 UTC, RPS98 commented on as2_behaviors/as2_behaviors_motion/land_behavior/plugins/land_plugin_speed.cpp
> +  float height_threshold_ = 0.2;
Should be. Check #155

2023-02-16 10:09 UTC, RPS98 commented on as2_behaviors/as2_behaviors_trajectory_generator/dynamic_polynomial_trajectory_generator/src/dynamic_polynomial_trajectory_generator.cpp
> -  // if (goal->trajectory_waypoints.header.frame_id != desired_frame_id_) {
Use TF to convert inputs frames to odom frame

2023-02-17 19:14 UTC, RPS98 commented
Done in pull request #163

2023-02-17 19:14 UTC, closed without merging