[as2_gazebo_assets] Fix malformed bridges
aerostack2/aerostack2 pull request #500
Opened 2024-05-16 09:40 UTC by pariaspe

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   | #499 |
| ROS2 version tested on | Humble |
| Aerial platform tested on | Gazebo |

---

## Description of contribution in a few bullet points

* Fixed lidar sensor

2024-05-16 09:45 UTC, pariaspe commented
Drafting until review all sensors. Camera already fixed in #450

2024-06-17 15:13 UTC, miferco97 requested changes

2024-06-17 15:13 UTC, miferco97 commented on as2_simulation_assets/as2_gazebo_assets/src/as2_gazebo_assets/bridges/bridges.py
> +    print(sensor_prefix + "\n")
Check double-quotes and long lines issues with flake8

2024-06-19 13:49 UTC, miferco97 approved these changes

2024-06-19 13:49 UTC, merged