dockerfile for working with gz harmonic
aerostack2/aerostack2 pull request #532
Opened 2024-06-17 11:08 UTC by fjanguita

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   |  |
| ROS2 version tested on | Humble |
| Aerial platform tested on | Gazebo |

---

## Description of contribution in a few bullet points

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

2024-06-17 11:17 UTC, miferco97 reviewed
The docker is ROOT, no sudo is needed

2024-06-17 12:26 UTC, RPS98 requested changes

2024-06-17 12:26 UTC, RPS98 commented on docker/humble_gzharmonic/dockerfile
> +RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
If already using aerostack2 image, this lines are not necessary, as they are duplicated

2024-06-17 12:26 UTC, RPS98 commented on docker/humble_gzharmonic/dockerfile
> +# Install Gazebo Harmonic
Use more RUN instructions instead of concatenating commands with &&. This is helpful for debugging when a build fails.

2024-06-17 12:26 UTC, RPS98 commented on docker/humble_gzharmonic/dockerfile
> +# Install common tools
Check if this it necessary

2024-06-17 12:26 UTC, RPS98 commented on docker/humble_gzharmonic/dockerfile
> +RUN . /opt/ros/$ROS_DISTRO/setup.sh && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
Must run this in aerostack2_ws

2024-06-18 07:54 UTC, RPS98 requested changes

2024-06-18 07:54 UTC, RPS98 commented on docker/humble_gzharmonic/dockerfile
> +# Install common tools
Works without it?

2024-06-18 08:02 UTC, miferco97 approved these changes

2024-06-18 08:21 UTC, fjanguita commented on docker/humble_gzharmonic/dockerfile
> +# Install common tools
it does, i forgot to remove comments

2024-06-18 08:38 UTC, RPS98 approved these changes

2024-06-18 15:21 UTC, merged