[as2_user_interfaces] add as2_viz package
aerostack2/aerostack2 pull request #601
Opened 2024-07-17 10:27 UTC by javilinos

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   |#600|
| ROS2 version tested on |Humble|
| Aerial platform tested on | Gazebo|

---

## Description of contribution in a few bullet points

* Added as2_viz package to visualize models

2024-07-17 12:39 UTC, RPS98 approved these changes

2024-07-17 12:40 UTC, RPS98 requested changes
Review package name and folder

2024-07-17 13:09 UTC, pariaspe commented
Let's archive the original repo after merging this @RPS98

2024-07-18 09:25 UTC, RPS98 approved these changes

2024-07-18 09:25 UTC, merged